class LiveWriter:
    def __init__(self, ensured_json: str) -> None: ...
    def write_f32_interleaved_live(self, frames: object) -> int: ...
    def clear_unread(self) -> int: ...
    def flush_silence(self) -> None: ...
    def close(self) -> None: ...
